# Generated by Django 6.0.7 on 2026-08-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stripe_payment_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Статус платежа'),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID сессии Stripe'),
        ),
    ]
